title: "AWS CI/CD Deployment"
description: "Setting up a Continuous Integration and Continuous Deployment pipeline for a web application using AWS services."

remote_theme: jekyll-theme-cayman@0.1.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

show_downloads: false

# Author details
author:
  name: Pavithra

# Repository info
repository: amie2001/aws-ci-cd

# Optional footer or intro
footer_text: >
  ðŸ‘‰ To know more about this project, visit the 
  [GitHub repository](https://github.com/amie2001/aws-ci-cd)

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
